### ISSUE TITLE
why 404

### ISSUE THREAD

**Issue by Curtaingit** [AndySpider/uicloner-extension#2]
Something went wrong, please check.
404 Invalid URL (POST /v1/images/generations/chat/completions) Troubleshooting URL: https://js.langchain.com/docs/troubleshooting/errors/MODEL_NOT_FOUND/

![image](https://github.com/user-attachments/assets/407ba48c-65d5-4f65-9d82-eb4277a25502)

**Comment by Curtaingit** [comment]
![image](https://github.com/user-attachments/assets/9214d632-8615-4dcc-bc1e-b290d75f3d37)

**Comment by AndySpider** [comment]
As the error message said, please check if the model name you specified is valid.

**Comment by AndySpider** [comment]
Fixed in 01.1, add predefined providers and models
