### ISSUE TITLE
please provide a basic configuration so we dont need to check what is wrong

### ISSUE THREAD

**Issue by oscarcalvo** [AndySpider/uicloner-extension#3]
I am triying with this one and it says me is incorrect because doesnt found the model

![image](https://github.com/user-attachments/assets/4f9a19a3-9056-4809-960c-ab4f6e505b82)

**Comment by AndySpider** [comment]
![llm-settings](https://github.com/user-attachments/assets/c952c249-4e0c-4091-8cd1-095701d8e355)
Fixed in 01.1
